name: flutter_tappay_sdk_spaceshare
description: 'flutter_tappay_sdk_spaceshare: a cross-platform Flutter wrapper for TapPay.'
version: 0.3.1
homepage: https://github.com/WeiHuangTaiwan/flutter_tappay_sdk_spaceshare

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: kent.chien.flutter_tappay_sdk_spaceshare
        pluginClass: FlutterTapPaySdkPlugin
      ios:
        pluginClass: FlutterTapPaySdkPlugin
      web:
        pluginClass: FlutterTapPaySdkWeb
        fileName: flutter_tappay_sdk_spaceshare_web.dart
